name: Instagram Uploader Service

on:
  workflow_dispatch:

jobs:
  run-service:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Ngrok and Start Server in Background
        shell: pwsh
        run: |
          # دانلود Ngrok
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          
          # ** FIX: استخراج در پوشه فعلی (.) **
          Expand-Archive -Path "ngrok.zip" -DestinationPath .
          
          # تنظیم توکن Ngrok
          ./ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          
          # اجرای Ngrok در پس‌زمینه
          Start-Process -FilePath "./ngrok.exe" -ArgumentList "http 3000" -NoNewWindow
          
          Start-Sleep -Seconds 10 
          
          # دریافت و چاپ URL عمومی
          $ngrokUrl = (Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels").tunnels[0].public_url
          Write-Host ">>>>>>>>>> Your public URL is: $ngrokUrl <<<<<<<<<<"
          
          # اجرای سرور Node.js در پس‌زمینه
          Start-Process -FilePath "node" -ArgumentList "upload_server.js" -NoNewWindow
          
      - name: Keep Runner Alive
        run: |
          Start-Sleep -Seconds 21000
